apiVersion: v1
kind: Service
metadata:
  name: movie-recommender-service
spec:
  type: NodePort
  selector:
    app: movie-recommender
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008  # You can pick any port in the range 30000–32767
